[package]
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
name = "chapter-1-kernel"
version = "0.1.0"

[dependencies]
nvptx-builtins = "0.1"
math = { git = "https://github.com/nagisa/math.rs.git" }
